<?php

/**
 * Implements hook_entity_view().
 */

function opening_banner_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

    if ($entity->getEntityType()->id() === 'node') {
        $build['awesome'] = [
            '#markup' => '<marquee>We are open</marquee>',
            '#allowed_tags' => ['marquee'],
        ];
    }

}